# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-30 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20180701_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 19, 6, 21, 426000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
