# Generated by Django 2.0.4 on 2018-07-02 07:20

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurantlocation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[restaurants.validators.validate_category]),
        ),
    ]
